AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PyTransit

  Lambda functions to fetch and filter STM GTFS files in Python

Parameters: 
  ApiKeyStm:
    Description: The STM API Key
    Type: String
  ApiUrlStmTrip:
    Description: The STM API Trip URL
    Type: String
  ApiUrlStmVehicle:
    Description: The STM API Vehicle URL
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5 # Timeout in seconds
    MemorySize: 128

Resources:
####################### FETCH GTFS TRIP_UPDATES #######################
  STMFetchGTFSTripUpdates:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 15 # Timeout in seconds
      MemorySize: 256
      CodeUri: STM_Services/STM_Fetch_GTFS_TripUpdates/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tripUpdates
            Method: get
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm

####################### FETCH GTFS VEHICLE_POSISTIONS #######################
  STMFetchGTFSVehiclePositions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 10 # Timeout in seconds
      MemorySize: 128
      CodeUri: STM_Services/STM_Fetch_GTFS_VehiclePositions/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /vehiclePositions
            Method: get
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm

####################### FETCH GBFS STATION_STATUS #######################
  BIXIFetchGBFSStationStatus:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: "Fetch Bixi station status data and parse it into a parquet file that is then save on a s3 bucket"
      Timeout: 15 # Timeout in seconds
      MemorySize: 256
      CodeUri: BIXI_Services/BIXI_Fetch_GBFS_Station_Status/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  BIXIFetchGBFSStationStatusTrigger:
    Type: AWS::Events::Rule
    Properties:
      Description: "calls BIXIFetchGBFSStationStatus every minute (Same speed as the data is refreshed)"
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        #- Arn: BIXIFetchGBFSStationStatus.Arn
        - Arn: "arn:aws:lambda:ca-central-1:540243147841:function:py-transit-BIXIFetchGBFSStationStatus-9p32yxsf2Ase:Live"
          Id: "TargetFunction"
          Input: >-
            {
              "bucket_name": "monitoring-mtl-bixi-gtfs-station-status-dev",
              "url": "https://gbfs.velobixi.com/gbfs/en/station_status.json"
            }
  
  BIXIFetchGBFSStationStatusPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      #FunctionName: !GetAtt BIXIFetchGBFSStationStatus.Arn
      FunctionName: "arn:aws:lambda:ca-central-1:540243147841:function:py-transit-BIXIFetchGBFSStationStatus-9p32yxsf2Ase:Live"
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BIXIFetchGBFSStationStatusTrigger.Arn

####################### FETCH URL STATIC FILES #######################
  STMFetchUpdateGTFSStaticfiles:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 60 # Timeout in seconds
      MemorySize: 1024
      CodeUri: STM_Services/STM_Fetch_Update_GTFS_Static_files/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm
    
  STMFetchUpdateGTFSStaticfilesTrigger:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 6 * * ? *)
      State: ENABLED
      Targets:
        #- Arn: !GetAtt STMFetchUpdateGTFSStaticfiles.Arn
        - Arn: "arn:aws:lambda:ca-central-1:540243147841:function:py-transit-STMFetchUpdateGTFSStaticfiles-ZIHANQxsuB4h:Live"
          Id: "TargetFunction"
          Input: >-
            {
              "bucket_name": "monitoring-mtl-gtfs-static",
              "url": "https://www.stm.info/sites/default/files/gtfs/gtfs_stm.zip"
            }
          
  STMFetchUpdateGTFSStaticfilesPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      #FunctionName: !GetAtt STMFetchUpdateGTFSStaticfiles.Arn
      FunctionName: "arn:aws:lambda:ca-central-1:540243147841:function:py-transit-STMFetchUpdateGTFSStaticfiles-ZIHANQxsuB4h:Live"
      Principal: events.amazonaws.com
      SourceArn: !GetAtt STMFetchUpdateGTFSStaticfilesTrigger.Arn

####################### FILTER DAILY GTFS STATIC #######################
  STMFilterDailyGTFStaticfiles:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 180 # Timeout in seconds
      MemorySize: 2048
      CodeUri: STM_Services/STM_Filter_Daily_GTFS_Static_files/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm

  STMFilterDailyGTFStaticfilesTrigger:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 8 * * ? *)
      State: ENABLED
      Targets:
        #- Arn: !GetAtt STMFilterDailyGTFStaticfiles.Arn
        - Arn: "arn:aws:lambda:ca-central-1:540243147841:function:py-transit-STMFilterDailyGTFStaticfiles-K6loMTjiMjxu:Live"
          Id: "TargetFunction"
          Input: >-
            {
              "input_bucket": "monitoring-mtl-gtfs-static",
              "output_bucket": "monitoring-mtl-gtfs-static-daily",
              "timezone": "America/Montreal"
            }
          
  STMFilterDailyGTFStaticfilesPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      #FunctionName: !GetAtt STMFilterDailyGTFStaticfiles.Arn
      FunctionName: "arn:aws:lambda:ca-central-1:540243147841:function:py-transit-STMFilterDailyGTFStaticfiles-K6loMTjiMjxu:Live"
      Principal: events.amazonaws.com
      SourceArn: !GetAtt STMFilterDailyGTFStaticfilesTrigger.Arn

####################### ANALYZE #######################
  STMAnalyzeDailyStopsData:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 840 # Timeout in seconds
      MemorySize: 8192
      CodeUri: STM_Services/STM_Analyse_Daily_Stops_Data/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /AnalyzeDailyStopsData
            Method: get
      Environment:
          Variables:
            API_URL_STM_TRIP: !Ref ApiUrlStmTrip
            API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
            API_KEY_STM: !Ref ApiKeyStm

####################### CREATE DAILY STOPS INFO #######################
  STMCreateDailyStopsInfo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 60 # Timeout in seconds
      MemorySize: 1024
      CodeUri: STM_Services/STM_Create_Daily_Stops_Info/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /CreateDailyStopsInfo
            Method: get
      Environment:
            Variables:
              API_URL_STM_TRIP: !Ref ApiUrlStmTrip
              API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
              API_KEY_STM: !Ref ApiKeyStm

  STMMergeDailyGTFSVechiclePositions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 600 # Timeout in seconds
      MemorySize: 4096
      CodeUri: STM_Services/STM_Merge_Daily_GTFS_VehiclePositions/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /MergeDailyGTFSVehiclePositions
            Method: get
      Environment:
            Variables:
              API_URL_STM_TRIP: !Ref ApiUrlStmTrip
              API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
              API_KEY_STM: !Ref ApiKeyStm
    
Outputs:

  STMFetchGTFSTripUpdatesFunctionArn:
    Description: "STM Fetch GTFS Trip Updates Lambda Function ARN"
    Value: !GetAtt STMFetchGTFSTripUpdates.Arn

  STMFetchGTFSVehiclePositionsFunctionArn:
    Description: "STM Fetch GTFS Vehicle Positions Lambda Function ARN"
    Value: !GetAtt STMFetchGTFSVehiclePositions.Arn

  STMFetchUpdateGTFSStaticfilesFunctionArn:
    Description: "STM Fetch Update GTFS Static files Lambda Function ARN"
    Value: !GetAtt STMFetchUpdateGTFSStaticfiles.Arn

  STMFetchUpdateGTFSStaticfilesTriggerArn:
    Description: "ARN of the EventBridge Rule for STMFetchUpdateGTFSStaticfiles"
    Value: !GetAtt STMFetchUpdateGTFSStaticfilesTrigger.Arn

####### FILTER DAILY GTFS STATIC FILES ########
  STMFilterDailyGTFStaticfilesFunctionArn:
    Description: "STM Filter Daily GTFS Static files Lambda Function ARN"
    Value: !GetAtt STMFilterDailyGTFStaticfiles.Arn

  STMFilterDailyGTFStaticfilesTriggerArn:
    Description: "ARN of the EventBridge Rule for STMFilterDailyGTFStaticfiles"
    Value: !GetAtt STMFilterDailyGTFStaticfilesTrigger.Arn

  STMAnalyzeDailyStopsDataFunctionArn: 
    Description: "STM Analyze Daily Stops Data Lambda Function ARN"
    Value: !GetAtt STMAnalyzeDailyStopsData.Arn

  STMCreateDailyStopsInfoFunctionArn:
    Description: "STM Create Daily Stops Info files Lambda Function ARN"
    Value: !GetAtt STMCreateDailyStopsInfo.Arn

  STMMergeDailyGTFSVechiclePositionsFunctionArn:
    Description: "STM Merge Daily GTFS Vehicle Positions files into one single file Lambda Function ARN"
    Value: !GetAtt STMMergeDailyGTFSVechiclePositions.Arn

  ####### BIXI functions ########
  BIXIFetchGBFSStationStatusFunctionArn:
    Description: "BIXI Fetch Update GBFS Static files Lambda Function ARN"
    Value: !GetAtt BIXIFetchGBFSStationStatus.Arn

  BIXIFetchGBFSStationStatusTriggerArn:
    Description: "ARN of the EventBridge Rule for BIXIFetchGBFSStationStatus"
    Value: !GetAtt BIXIFetchGBFSStationStatusTrigger.Arn