AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PyTransit

  Lambda functions to fetch and filter STM GTFS files in Python

Parameters: 
  ApiKeyStm:
    Description: The STM API Key
    Type: String
  ApiUrlStmTrip:
    Description: The STM API Trip URL
    Type: String
  ApiUrlStmVehicle:
    Description: The STM API Vehicle URL
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5 # Timeout in seconds
    MemorySize: 128

Resources:

  STMFetchGTFSTripUpdates:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 15 # Timeout in seconds
      MemorySize: 256
      CodeUri: STM_Services/STM_Fetch_GTFS_TripUpdates/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tripUpdates
            Method: get
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm

  STMFetchGTFSVehiclePositions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: STM_Services/STM_Fetch_GTFS_VehiclePositions/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /vehiclePositions
            Method: get
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm

  STMFetchUpdateGTFSStaticfiles:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 60 # Timeout in seconds
      MemorySize: 1024
      CodeUri: STM_Services/STM_Fetch_Update_GTFS_Static_files/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fetchUpdate
            Method: get
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm

  STMFilterDailyGTFStaticfiles:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 60 # Timeout in seconds
      MemorySize: 2048
      CodeUri: STM_Services/STM_Filter_Daily_GTFS_Static_files/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /filter
            Method: get
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm

  STMAnalyzeDailyStopsData:
  Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  Properties:
    Timeout: 840 # Timeout in seconds
    MemorySize: 8096
    CodeUri: STM_Services/STM_Analyse_Daily_Stops_Data/
    Handler: main.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64
    Events:
      Start:
        Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        Properties:
          Path: /filter
          Method: get

  STMCreateDailyStopsInfo:
  Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  Properties:
    Timeout: 60 # Timeout in seconds
    MemorySize: 1024
    CodeUri: STM_Services/STM_Create_Daily_Stops_Info/
    Handler: main.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64
    Events:
      Start:
        Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        Properties:
          Path: /filter
          Method: get
    
Outputs:

  STMFetchGTFSTripUpdatesFunctionArn:
    Description: "STM Fetch GTFS Trip Updates Lambda Function ARN"
    Value: !GetAtt STMFetchGTFSTripUpdates.Arn

  STMFetchGTFSVehiclePositionsFunctionArn:
    Description: "STM Fetch GTFS Vehicle Positions Lambda Function ARN"
    Value: !GetAtt STMFetchGTFSVehiclePositions.Arn

  STMFetchUpdateGTFSStaticfilesFunctionArn:
    Description: "STM Fetch Update GTFS Static files Lambda Function ARN"
    Value: !GetAtt STMFetchUpdateGTFSStaticfiles.Arn

  STMFilterDailyGTFStaticfilesFunctionArn:
    Description: "STM Filter Daily GTFS Static files Lambda Function ARN"
    Value: !GetAtt STMFilterDailyGTFStaticfiles.Arn

  STMAnalyzeDailyStopsDataFunctionArn: 
    Description: "STM Analyze Daily Stops Data Lambda Function ARN"
    Value: !GetAtt STMAnalyzeDailyStopsData.Arn

  STMCreateDailyStopsInfoFunctionArn:
    Description: "STM Create Daily Stops Info files Lambda Function ARN"
    Value: !GetAtt STMCreateDailyStopsInfo.Arn

