AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PyTransit

  Lambda functions to fetch and filter STM GTFS files in Python

Parameters: 
  ApiKeyStm:
    Description: The STM API Key
    Type: String
  ApiUrlStmTrip:
    Description: The STM API Trip URL
    Type: String
  ApiUrlStmVehicle:
    Description: The STM API Vehicle URL
    Type: String
  UpdateCheck:
    Description: Checks if each function can be updated
    Type: CommaDelimitedList
    #AllowedValues:
    #  - "1"
    #  - "0"
    #  - ""

Conditions:
  SetBIXIFetchGBFSStationStatus: !Not [!Equals [!Select [0, !Ref UpdateCheck], "0"]]
  SetSTMAnalyzeDailyStopsData: !Not [!Equals [!Select [1, !Ref UpdateCheck], "0"]]
  SetSTMCreateDailyStopsInfo: !Not [!Equals [!Select [2, !Ref UpdateCheck], "0"]]
  SetSTMFetchGTFSTripUpdates: !Not [!Equals [!Select [3, !Ref UpdateCheck], "0"]]
  SetSTMFetchGTFSVehiclePositions: !Not [!Equals [!Select [4, !Ref UpdateCheck], "0"]]
  SetSTMFetchUpdateGTFSStaticfiles: !Not [!Equals [!Select [5, !Ref UpdateCheck], "0"]]
  SetSTMFilterDailyGTFStaticfiles: !Not [!Equals [!Select [6, !Ref UpdateCheck], "0"]]
  SetSTMMergeDailyGTFSVechiclePositions: !Not [!Equals [!Select [7, !Ref UpdateCheck], "0"]]

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5 # Timeout in seconds
    MemorySize: 128

Resources:
####################### FETCH GTFS TRIP_UPDATES #######################
  STMFetchGTFSTripUpdates:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 15 # Timeout in seconds
      MemorySize: 256
      CodeUri: STM_Services/STM_Fetch_GTFS_TripUpdates/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tripUpdates
            Method: get
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm

####################### FETCH GTFS VEHICLE_POSISTIONS #######################
  STMFetchGTFSVehiclePositions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 10 # Timeout in seconds
      MemorySize: 128
      CodeUri: STM_Services/STM_Fetch_GTFS_VehiclePositions/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /vehiclePositions
            Method: get
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm

####################### FETCH GBFS STATION_STATUS #######################
  BIXIFetchGBFSStationStatusRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
  
  BIXIFetchGBFSStationStatus:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: "Fetch Bixi station status data and parse it into a parquet file that is then save on a s3 bucket"
      Timeout: 15 # Timeout in seconds
      MemorySize: 256
      Role: !GetAtt BIXIFetchGBFSStationStatusRole.Arn
      CodeUri: BIXI_Services/BIXI_Fetch_GBFS_Station_Status/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  BIXIFetchGBFSStationStatusPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BIXIFetchGBFSStationStatusPolicy
      Roles:
        - !Ref BIXIFetchGBFSStationStatusRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: s3:PutObject
            Resource: arn:aws:s3:::monitoring-mtl-bixi-gtfs-station-status-dev/*

  BIXIFetchGBFSStationStatusVersion:
    Condition: SetBIXIFetchGBFSStationStatus
    Type: AWS::Lambda::Version
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: !Ref BIXIFetchGBFSStationStatus

  BIXIFetchGBFSStationStatusAlias:
    Condition: SetBIXIFetchGBFSStationStatus
    Type: AWS::Lambda::Alias
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: !Ref BIXIFetchGBFSStationStatus
      FunctionVersion: !GetAtt BIXIFetchGBFSStationStatusVersion.Version
      Name: Live

  BIXIFetchGBFSStationStatusTrigger:
    Type: AWS::Events::Rule
    Properties:
      Description: "calls BIXIFetchGBFSStationStatus every minute (Same speed as the data is refreshed)"
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        - Arn: !If [SetBIXIFetchGBFSStationStatus, !Ref BIXIFetchGBFSStationStatusAlias, !Join [":", [!GetAtt BIXIFetchGBFSStationStatus.Arn,"Live"]]]
          Id: "TargetBixiAlias"
          Input: >-
            {
              "bucket_name": "monitoring-mtl-bixi-gtfs-station-status-dev",
              "url": "https://gbfs.velobixi.com/gbfs/en/station_status.json"
            }
  
  BIXIFetchGBFSStationStatusPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !If [SetBIXIFetchGBFSStationStatus, !Ref BIXIFetchGBFSStationStatusAlias, !Join [":", [!GetAtt BIXIFetchGBFSStationStatus.Arn,"Live"]]]
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BIXIFetchGBFSStationStatusTrigger.Arn

####################### FETCH URL STATIC FILES #######################
  STMFetchUpdateGTFSStaticfiles:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 60 # Timeout in seconds
      MemorySize: 1024
      CodeUri: STM_Services/STM_Fetch_Update_GTFS_Static_files/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm
  
  STMFetchUpdateGTFSStaticfilesVersion:
    Condition: SetSTMFetchUpdateGTFSStaticfiles
    Type: AWS::Lambda::Version
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: !Ref STMFetchUpdateGTFSStaticfiles

  STMFetchUpdateGTFSStaticfilesAlias:
    Condition: SetSTMFetchUpdateGTFSStaticfiles
    Type: AWS::Lambda::Alias
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: !Ref STMFetchUpdateGTFSStaticfiles
      FunctionVersion: !GetAtt STMFetchUpdateGTFSStaticfilesVersion.Version
      Name: Live
    
  STMFetchUpdateGTFSStaticfilesTrigger:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 6 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !If [SetSTMFetchUpdateGTFSStaticfiles, !Ref STMFetchUpdateGTFSStaticfilesAlias, !Join [":", [!GetAtt STMFetchUpdateGTFSStaticfiles.Arn,"Live"]]]
          Id: "TargetFunction"
          Input: >-
            {
              "bucket_name": "monitoring-mtl-gtfs-static",
              "url": "https://www.stm.info/sites/default/files/gtfs/gtfs_stm.zip"
            }
          
  STMFetchUpdateGTFSStaticfilesPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !If [SetSTMFetchUpdateGTFSStaticfiles, !Ref STMFetchUpdateGTFSStaticfilesAlias, !Join [":", [!GetAtt STMFetchUpdateGTFSStaticfiles.Arn,"Live"]]]
      Principal: events.amazonaws.com
      SourceArn: !GetAtt STMFetchUpdateGTFSStaticfilesTrigger.Arn

####################### FILTER DAILY GTFS STATIC #######################
  STMFilterDailyGTFStaticfiles:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 180 # Timeout in seconds
      MemorySize: 2048
      CodeUri: STM_Services/STM_Filter_Daily_GTFS_Static_files/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_URL_STM_TRIP: !Ref ApiUrlStmTrip
          API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
          API_KEY_STM: !Ref ApiKeyStm

  STMFilterDailyGTFStaticfilesVersion:
    Condition: SetSTMFilterDailyGTFStaticfiles
    Type: AWS::Lambda::Version
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: !Ref STMFilterDailyGTFStaticfiles

  STMFilterDailyGTFStaticfilesAlias:
    Condition: SetSTMFilterDailyGTFStaticfiles
    Type: AWS::Lambda::Alias
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: !Ref STMFilterDailyGTFStaticfiles
      FunctionVersion: !GetAtt STMFilterDailyGTFStaticfilesVersion.Version
      Name: Live

  STMFilterDailyGTFStaticfilesTrigger:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 8 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !If [SetSTMFilterDailyGTFStaticfiles, !Ref STMFilterDailyGTFStaticfilesAlias, !Join [":", [!GetAtt STMFilterDailyGTFStaticfiles.Arn,"Live"]]]
          Id: "TargetFunction"
          Input: >-
            {
              "input_bucket": "monitoring-mtl-gtfs-static",
              "output_bucket": "monitoring-mtl-gtfs-static-daily",
              "timezone": "America/Montreal"
            }
          
  STMFilterDailyGTFStaticfilesPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !If [SetSTMFilterDailyGTFStaticfiles, !Ref STMFilterDailyGTFStaticfilesAlias, !Join [":", [!GetAtt STMFilterDailyGTFStaticfiles.Arn,"Live"]]]
      Principal: events.amazonaws.com
      SourceArn: !GetAtt STMFilterDailyGTFStaticfilesTrigger.Arn

####################### ANALYZE #######################
  STMAnalyzeDailyStopsData:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 840 # Timeout in seconds
      MemorySize: 8192
      CodeUri: STM_Services/STM_Analyse_Daily_Stops_Data/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /AnalyzeDailyStopsData
            Method: get
      Environment:
          Variables:
            API_URL_STM_TRIP: !Ref ApiUrlStmTrip
            API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
            API_KEY_STM: !Ref ApiKeyStm

####################### CREATE DAILY STOPS INFO #######################
  STMCreateDailyStopsInfo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 60 # Timeout in seconds
      MemorySize: 1024
      CodeUri: STM_Services/STM_Create_Daily_Stops_Info/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /CreateDailyStopsInfo
            Method: get
      Environment:
            Variables:
              API_URL_STM_TRIP: !Ref ApiUrlStmTrip
              API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
              API_KEY_STM: !Ref ApiKeyStm

  STMMergeDailyGTFSVechiclePositions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 600 # Timeout in seconds
      MemorySize: 4096
      CodeUri: STM_Services/STM_Merge_Daily_GTFS_VehiclePositions/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /MergeDailyGTFSVehiclePositions
            Method: get
      Environment:
            Variables:
              API_URL_STM_TRIP: !Ref ApiUrlStmTrip
              API_URL_STM_VEHICLE: !Ref ApiUrlStmVehicle
              API_KEY_STM: !Ref ApiKeyStm
    
Outputs:

  BIXIFetchGBFSStationStatusUpdateStatus:
    Description: "Has BIXIFetchGBFSStationStatus been updated?"
    Value: !If [SetBIXIFetchGBFSStationStatus, !Join [" ", ["Yes. It is now version:",!GetAtt BIXIFetchGBFSStationStatusVersion.Version]], "No"]

  STMAnalyzeDailyStopsDataUpdateStatus:
    Description: "Has STMAnalyzeDailyStopsData been updated?"
    Value: !If [SetSTMAnalyzeDailyStopsData, "Yes", "No"]

  STMCreateDailyStopsInfoUpdateStatus:
    Description: "Has STMCreateDailyStopsInfo been updated?"
    Value: !If [SetSTMCreateDailyStopsInfo, "Yes", "No"]

  STMFetchGTFSTripUpdatesUpdateStatus:
    Description: "Has STMFetchGTFSTripUpdates been updated?"
    Value: !If [SetSTMFetchGTFSTripUpdates, "Yes", "No"]
  
  STMFetchGTFSVehiclePositionsUpdateStatus:
    Description: "Has STMFetchGTFSVehiclePositions been updated?"
    Value: !If [SetSTMFetchGTFSVehiclePositions, "Yes", "No"]

  STMFetchUpdateGTFSStaticfilesUpdateStatus:
    Description: "Has STMFetchUpdateGTFSStaticfiles been updated?"
    Value: !If [SetSTMFetchUpdateGTFSStaticfiles, !Join [" ", ["Yes. It is now version:",!GetAtt STMFetchUpdateGTFSStaticfilesVersion.Version]], "No"]

  STMFilterDailyGTFStaticfilesStatus:
    Description: "Has STMFilterDailyGTFStaticfiles been updated?"
    Value: !If [SetSTMFilterDailyGTFStaticfiles, !Join [" ", ["Yes. It is now version:",!GetAtt STMFilterDailyGTFStaticfilesVersion.Version]], "No"]

  STMMergeDailyGTFSVechiclePositionsUpdateStatus:
    Description: "Has STMMergeDailyGTFSVechiclePositions been updated?"
    Value: !If [SetSTMMergeDailyGTFSVechiclePositions, "Yes", "No"]

