@startuml mainfunction
participant "transform_load_csv" as fn
queue ":Queue" as Queue
collections ":Worker" as Worker
collections "chunks:Iterator" as chunks

-> fn: execute
activate fn
fn -> Queue ** : create
fn -> Worker ** : create with queue

fn -> chunks** : create from CSV file
loop while exist chunks
fn -> chunks: read chunk
fn -> Queue : put process_locations with chunk
fn -> Queue : put process_trips with chunk
end

fn -> Worker !!
fn -> Queue !!
return

@enduml
