@startuml model
Title: Trips model

class StationLocation {
  name: string
  arrondissement: string
  latitude: float
  longitude: float
}

class Trip {
  id: int
  start_station_name: int
  end_station_name: int
  star_time_ms: int
  end_time_ms: int
}

Trip "1" -> "2" StationLocation 

@enduml
