@startuml trips
participant ":Worker" as w
participant "process_trips" as fn
collections "chunk" as chunk
database "MongoDb" as m

w -> fn: execute
activate fn
fn -> chunk: remove unnecessary columns
fn -> chunk: calculate and add duration column
fn -> fn: build insertion operations
fn -> m: bulk write operations
return
@enduml
