@startuml work
participant "w1:Worker" as w1
collections "..." as w2
queue ":Queue" as Queue

activate w1
activate w2
par
loop until stopped
w1 -> Queue: get task
w1 -> w1: execute task
w1 -> Queue: done task
end loop
else
loop until stopped
w2 -> Queue: get task
w2 -> w2: execute task
w2 -> Queue: done task
end loop
end

@enduml
