name: Deploy Lambda Functions to AWS

on: 
    push:
        branches:
        - main
        paths:
        - 'STM_Services/**'
    workflow_dispatch:


jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Build and Deploy to AWS

        steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1-node16
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ca-central-1  # Change to your preferred AWS region        - 

        - name: Build and Deploy to AWS
          env:
            API_KEY_STM: ${{ secrets.API_KEY_STM }}
            API_URL_STM_TRIP: ${{ secrets.API_URL_STM_TRIP}}
            API_URL_STM_VEHICLE: ${{ secrets.API_URL_STM_VEHICLE}}
          run: |
            sam build
            sam deploy --parameter-overrides ApiUrlStmTrip=$API_URL_STM_TRIP ApiKey=$API_KEY_STM ApiUrlStmVehicle=$API_URL_STM_VEHICLE