name: Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "BIXI_Services/**"
      - "STM_Services/**"
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to AWS

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Execute Versioning.py and save results
        run: |
          # Install the json file package
          sudo apt-get install jq -y
          python -c 'from versioning import main; main()' 
          # Scripts create JSON file so we assign the results to variables
          BIXI=$(jq -r '.BIXIFetchGBFSStationStatus' functions.json)
          STMAnalyzeDailyStop=$(jq -r '.STMAnalyzeDailyStopsData' functions.json)
          STMCreateDailyStop=$(jq -r '.STMCreateDailyStopsInfo' functions.json)
          STMFetchTripUpdates=$(jq -r '.STMFetchGTFSTripUpdates' functions.json)
          STMFetchVehiclePositions=$(jq -r '.STMFetchGTFSVehiclePositions' functions.json)
          STMFetchUpdateStatic=$(jq -r '.STMFetchUpdateGTFSStaticfiles' functions.json)
          STMFilterDailyStatic=$(jq -r '.STMFilterDailyGTFStaticfiles' functions.json)
          STMMergeDailyVehiclePosition=$(jq -r '.STMMergeDailyGTFSVechiclePositions' functions.json)
          BixiHistoricDataChecker=$(jq -r '.BixiHistoricDataCheckerLambda' function.json)
          BixiHistoricDataProcessor=$(jq -r '.BixiHistoricDataProcessorLambda' function.json)
          today=$(date '+%Y-%m-%d')
          # Set environment variables
          echo "BIXI=$BIXI" >> $GITHUB_ENV
          echo "STMAnalyzeDailyStop=$STMAnalyzeDailyStop" >> $GITHUB_ENV
          echo "STMCreateDailyStop=$STMCreateDailyStop" >> $GITHUB_ENV
          echo "STMFetchTripUpdates=$STMFetchTripUpdates" >> $GITHUB_ENV
          echo "STMFetchVehiclePositions=$STMFetchVehiclePositions" >> $GITHUB_ENV
          echo "STMFetchUpdateStatic=$STMFetchUpdateStatic" >> $GITHUB_ENV
          echo "STMFilterDailyStatic=$STMFilterDailyStatic" >> $GITHUB_ENV
          echo "STMMergeDailyVehiclePosition=$STMMergeDailyVehiclePosition" >> $GITHUB_ENV
          echo "BixiHistoricDataChecker=$BixiHistoricDataChecker" >> $GITHUB_ENV
          echo "BixiHistoricDataProcessor=$BixiHistoricDataProcessor" >> $GITHUB_ENV
          echo "today=$today" >> $GITHUB_ENV

      - name: Build and Deploy to AWS
        env:
          API_KEY_STM: ${{ secrets.API_KEY_STM }}
          API_URL_STM_TRIP: ${{ secrets.API_URL_STM_TRIP }}
          API_URL_STM_VEHICLE: ${{ secrets.API_URL_STM_VEHICLE }}
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          MONGO_DATABASE_NAME: ${{ vars.MONGO_DATABASE_NAME }}
          BIXI_DATA_URL: ${{ vars.BIXI_DATA_URL }}
          BIXI_CDN: ${{ vars.BIXI_CDN }}
          BIXI_URL_COLLECTION: ${{ vars.BIXI_URL_COLLECTION }}
          BIXI_DEFAULT_EXTRACT_PATH: ${{ vars.BIXI_DEFAULT_EXTRACT_PATH }}
          BIXI_LOCATION_COLLECTION: ${{ vars.BIXI_LOCATION_COLLECTION }}
          BIXI_TRIP_COLLECTION: ${{ vars.BIXI_TRIP_COLLECTION }}
          BIXI_CHUNK_SIZE: ${{ vars.BIXI_CHUNK_SIZE }}
        run: |
          sam build
          sam deploy --parameter-overrides \
            ApiUrlStmTrip=$API_URL_STM_TRIP \
            ApiKey=$API_KEY_STM \
            ApiUrlStmVehicle=$API_URL_STM_VEHICLE \
            Date=$today \
            AtlasUri=$ATLAS_URI \
            MongoDatabaseName=$MONGO_DATABASE_NAME \
            BixiDataUrl=$BIXI_DATA_URL \
            BixiCdn=$BIXI_CDN \
            BixiUrlCollection=$BIXI_URL_COLLECTION \
            BixiDefaultExtractPath=$BIXI_DEFAULT_EXTRACT_PATH \
            BixiLocationCollection=$BIXI_LOCATION_COLLECTION \
            BixiTripCollection=$BIXI_TRIP_COLLECTION \
            BixiChunkSize=$BIXI_CHUNK_SIZE \
            UpdateCheck="${BIXI},${STMAnalyzeDailyStop},${STMCreateDailyStop},${STMFetchTripUpdates},${STMFetchVehiclePositions},${STMFetchUpdateStatic},${STMFilterDailyStatic},${STMMergeDailyVehiclePosition}"

      - name: Delete JSON File
        run: rm functions.json
