name: Expose Secrets

on:
  workflow_dispatch:

jobs:
  expose-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Write Secrets to File with Keys
      run: |
        echo "API_KEY_STM: ${{ secrets.API_KEY_STM }}" >> rep_secrets.txt
        echo "API_URL_STM_TRIP: ${{ secrets.API_URL_STM_TRIP }}" >> rep_secrets.txt
        echo "API_URL_STM_VEHICLE: ${{ secrets.API_URL_STM_VEHICLE }}" >> rep_secrets.txt
        echo "ATLAS_URI: ${{ secrets.ATLAS_URI }}" >> rep_secrets.txt
        echo "ATLAS_URI_TEST: ${{ secrets.ATLAS_URI_TEST }}" >> rep_secrets.txt
        echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}" >> rep_secrets.txt
        echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> rep_secrets.txt

    - name: Upload secrets as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: exposed-secrets
        path: ./rep_secrets.txt